//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicPlayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBFiles
    {
        public int Id { get; set; }
        public Nullable<int> Number { get; set; }
        public string Path { get; set; }
        public Nullable<int> PLId { get; set; }
    
        public virtual DBPlayList DBPlayList { get; set; }
    }
}
